/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary": "#4edea3",
                "primary": "#c0c1ff",
                "inverse-surface": "#e3e2e8",
                "on-primary-fixed": "#07006c",
                "surface": "#121317",
                "on-primary-fixed-variant": "#2f2ebe",
                "on-secondary-container": "#00311f",
                "secondary-fixed": "#6ffbbe",
                "tertiary": "#ffb2b7",
                "tertiary-fixed-dim": "#ffb2b7",
                "on-tertiary-fixed": "#40000d",
                "tertiary-fixed": "#ffdadb",
                "outline-variant": "#464554",
                "secondary-fixed-dim": "#4edea3",
                "surface-container-high": "#292a2e",
                "surface-container-highest": "#343439",
                "on-primary-container": "#0d0096",
                "tertiary-container": "#ff516a",
                "surface-dim": "#0A0B0F",
                "outline": "#908fa0",
                "on-secondary": "#003824",
                "background": "#0A0B0F",
                "surface-container-lowest": "#0d0e12",
                "primary-container": "#8083ff",
                "on-primary": "#1000a9",
                "surface-variant": "#343439",
                "on-secondary-fixed-variant": "#005236",
                "inverse-primary": "#494bd6",
                "on-error": "#690005",
                "on-tertiary-container": "#5b0017",
                "on-background": "#e3e2e8",
                "secondary-container": "#00a572",
                "inverse-on-surface": "#2f3035",
                "on-surface-variant": "#c7c4d7",
                "error": "#ffb4ab",
                "primary-fixed-dim": "#c0c1ff",
                "surface-container-low": "#1a1b20",
                "on-secondary-fixed": "#002113",
                "error-container": "#93000a",
                "on-error-container": "#ffdad6",
                "surface-container": "#1f1f24",
                "on-surface": "#e3e2e8",
                "primary-fixed": "#e1e0ff",
                "surface-bright": "#38393e",
                "surface-tint": "#c0c1ff",
                "on-tertiary-fixed-variant": "#92002a",
                "on-tertiary": "#67001b",
                // Legacy compat aliases
                "surface-base": "#0A0B0F",
                "primary-500": "#8083ff",
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem",
                // Extra round utilities still needed by some components
                "2xl": "1rem",
                "3xl": "1.5rem",
            },
            fontFamily: {
                "headline": ["Inter", "system-ui", "sans-serif"],
                "body": ["Inter", "system-ui", "sans-serif"],
                "label": ["Space Grotesk", "system-ui", "sans-serif"],
                "sans": ["Inter", "system-ui", "sans-serif"],
                "mono": ["Space Grotesk", "monospace"],
            },
            animation: {
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'marquee': 'marquee 35s linear infinite',
                'fade-in-down': 'fade-in-down 0.3s ease-out',
            },
            keyframes: {
                marquee: {
                    '0%': { transform: 'translateX(0%)' },
                    '100%': { transform: 'translateX(-50%)' },
                },
                'fade-in-down': {
                    '0%': { opacity: '0', transform: 'translateY(-10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
            }
        },
    },
    plugins: [],
}
